using CMS.Controller;
using CMS.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace CMS.View.Patient
{
    // Partial class for the ViewPrescription Windows Form
    public partial class ViewPrescription : Form
    {
        private int _patientId; // Stores the currently logged-in patient ID

        // Constructor - accepts patientId and stores it
        public ViewPrescription(int patientId)
        {
            InitializeComponent();  // Initializes form controls (auto-generated by Designer)
            _patientId = patientId; // Save the patient ID for later use
        }

        // This method runs when the form loads
        private void ViewPrescription_Load(object sender, EventArgs e)
        {
            // Define 5 columns for the DataGridView (you can skip this if already done in Designer)
            dgvPrescriptions.ColumnCount = 5;

            // Set each column's header text
            dgvPrescriptions.Columns[0].Name = "PrescriptionID";   // Internal ID (hidden)
            dgvPrescriptions.Columns[1].Name = "Date";              // Prescription date
            dgvPrescriptions.Columns[2].Name = "Doctor Name";       // Doctor's full name
            dgvPrescriptions.Columns[3].Name = "Diagnosis";         // Diagnosis details
            dgvPrescriptions.Columns[4].Name = "Medicines";         // Medicine description

            // Hide the PrescriptionID column from the user (used internally only)
            dgvPrescriptions.Columns[0].Visible = false;

            // Call the method to load data into the DataGridView
            LoadPrescriptions(_patientId);
        }

        // This method connects to the controller and fetches prescriptions for the given patient
        private void LoadPrescriptions(int patientId)
        {
            var controller = new PrescriptionController();  // Create an instance of the controller
            var prescriptions = controller.GetPrescriptionsByPatientId(patientId);  // Get list of prescriptions

            dgvPrescriptions.Rows.Clear();  // Clear existing rows from the grid

            // Loop through each prescription and add it to the DataGridView
            foreach (var p in prescriptions)
            {
                dgvPrescriptions.Rows.Add(
                    p.PrescriptionID,                         // Hidden column for internal use
                    p.PrescriptionDate.ToShortDateString(),   // Display short date format
                    p.Doctor.Name,                            // Show doctor's name
                    p.Diagnosis,                              // Diagnosis given
                    p.Medicines                               // Prescribed medicines
                );
            }
        }

        // This method runs when the "Back" button is clicked
        private void btnBack_Click(object sender, EventArgs e)
        {
            this.Close();  // Close the form and return to previous screen
        }

    }
}
